trigger:
  branches:
    include:
      - master
      - feature/*
      - fix/*

resources:
  repositories:
    - repository: pipeline-library
      type: github
      endpoint: quantum-sec-github
      name: quantum-sec/pipeline-library

jobs:
  - template: templates/validation/pre-commit.yml@pipeline-library
  - template: templates/versioning/semantic-release.yml@pipeline-library
    parameters:
      dependsOn:
        - PreCommit
